apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "external-dns.fullname" . }}-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: cloudflare-credentials
    creationPolicy: Owner
  data:
  - secretKey: cloudflare_api_token
    remoteRef:
      key: ops/cloudflare-api-token
      conversionStrategy: Default
      decodingStrategy: None
