apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "app.fullname" . }}
  name: {{ include "app.fullname" . }}-ev
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
data:
  {{- range $name, $value := .Values.env }}
  {{ $name }}: {{ required (printf "key %s is missing from .Values.env" $name) $value | quote}}
  {{- end }}
  {{- if not .Values.postgresql.enabled }}
  {{ if and (not .Values.postgresql.enabled) (not .Values.pr.connectToReplica) }}
  TYPEORM_DATABASE: {{ .Values.env.DATABASE_NAME }}
  {{ end }}
  {{ if and (not .Values.postgresql.enabled) .Values.pr.connectToReplica }}
  TYPEORM_DATABASE: "bery"
  {{ end }}
  TYPEORM_DRIVER_EXTRA: '{"ssl": { "rejectUnauthorized": false }, "max": 20}'
  {{- else }}
  TYPEORM_DATABASE: {{ .Values.postgresql.auth.database }}
  {{- end }}
