apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  acme:
    email: ops.group+letsencrypt@xbery.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.email }}
          apiTokenSecretRef:
            name: cloudflare-credentials
            key: cloudflare_api_token
