apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "external-dns.fullname" . }}-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: basic-auth
    creationPolicy: Owner
  data:
  - secretKey: auth
    remoteRef:
      key: ops/prometheus-basic-auth
      conversionStrategy: Default
      decodingStrategy: None
  - secretKey: PROMETHEUS_BASIC_AUTH_USER_PASSWORD
    remoteRef:
      key: ops/prometheus-basic-auth-user-password
      conversionStrategy: Default
      decodingStrategy: None
  - secretKey: AWS_MAIN_ACCOUNT_ACCESS_KEY_ID
    remoteRef:
      key: ops/aws-main-account-access-key-id
      conversionStrategy: Default
      decodingStrategy: None
  - secretKey: AWS_MAIN_ACCOUNT_SECRET_KEY
    remoteRef:
      key: ops/aws-main-account-secret-key
      conversionStrategy: Default
      decodingStrategy: None
  - secretKey: AWS_OPS_HUB_ACCOUNT_ACCESS_KEY_ID
    remoteRef:
      key: ops/aws-ops-hub-account-access-key-id
      conversionStrategy: Default
      decodingStrategy: None
  - secretKey: AWS_OPS_HUB_ACCOUNT_SECRET_KEY
    remoteRef:
      key: ops/aws-ops-hub-account-secret-key
      conversionStrategy: Default
      decodingStrategy: None
