apiVersion: v2
name: cert-manger
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.1"
dependencies:
- name: cert-manager
  repository: https://charts.jetstack.io
  version: 1.12.*
